# Generated by Django 4.1.1 on 2022-09-27 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0003_auto_20220123_1955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="Date_Time",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 9, 27, 18, 0, 25, 477078, tzinfo=datetime.timezone.utc
                ),
                max_length=19,
            ),
        ),
    ]
